# Generated by Django 3.2.6 on 2021-10-01 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45, null=True)),
                ('middle_name', models.CharField(max_length=45, null=True)),
                ('nickname', models.CharField(max_length=45, null=True)),
                ('name_pronunciation', models.CharField(max_length=45, null=True)),
                ('pronouns', models.CharField(choices=[('he/him', 'Mal'), ('she/her', 'Fem'), ('they/them', 'Oth')], max_length=15, null=True)),
                ('title', models.CharField(max_length=45, null=True)),
                ('relation', models.CharField(max_length=45, null=True)),
                ('company', models.CharField(max_length=45, null=True)),
                ('job_title', models.CharField(max_length=45, null=True)),
                ('side_notes', models.TextField(null=True)),
                ('department', models.CharField(max_length=45, null=True)),
                ('regularity_of_contact', models.IntegerField(choices=[(104, 'Wk2'), (52, 'Wk1'), (26, 'Frnt'), (12, 'Mnth'), (6, 'Bimt'), (2, 'Yr2'), (1, 'Yr1')], null=True)),
                ('last_time_contacted', models.DateTimeField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportantDateType',
            fields=[
                ('label', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('icon', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaSite',
            fields=[
                ('site', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('icon', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=45)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_book.contact')),
                ('social_media_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_book.socialmediasite')),
            ],
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=18)),
                ('label', models.CharField(choices=[('business', 'Bus'), ('friend', 'Frn'), ('family', 'Fam'), ('other', 'Oth')], max_length=15, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_book.contact')),
            ],
        ),
        migrations.CreateModel(
            name='ImportantDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('get_alert', models.BooleanField()),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_book.contact')),
                ('important_date_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_book.socialmediasite')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=45)),
                ('label', models.CharField(choices=[('business', 'business'), ('friend', 'friend'), ('family', 'family'), ('other', 'other')], max_length=15)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_book.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=45)),
                ('postcode', models.CharField(max_length=10)),
                ('address_line_one', models.CharField(max_length=45)),
                ('address_line_two', models.CharField(max_length=45)),
                ('suburb', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('start_of_habitation', models.DateTimeField(null=True)),
                ('end_of_habitation', models.DateTimeField(null=True)),
                ('is_current', models.BooleanField()),
                ('is_hometown', models.BooleanField(null=True)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_book.contact')),
                ('login_of_host_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
