# Generated by Django 3.2.6 on 2021-09-27 04:59

import apps.contact_book.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45, null=True)),
                ('middle_name', models.CharField(max_length=45, null=True)),
                ('nickname', models.CharField(max_length=45, null=True)),
                ('name_pronunciation', models.CharField(max_length=45, null=True)),
                ('pronouns', models.CharField(choices=[(apps.contact_book.models.PronounsChoice['MAL'], 'he/him'), (apps.contact_book.models.PronounsChoice['FEM'], 'she/her'), (apps.contact_book.models.PronounsChoice['OTH'], 'they/them')], max_length=15, null=True)),
                ('last_time_contacted', models.DateTimeField(null=True)),
                ('login_of_host_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportantDateType',
            fields=[
                ('label', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('icon', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaSite',
            fields=[
                ('site', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('icon', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=45)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_book.contact')),
                ('social_media_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_book.socialmediasite')),
            ],
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=18)),
                ('label', models.CharField(choices=[(apps.contact_book.models.ContactMediumLabel['BUS'], 'business'), (apps.contact_book.models.ContactMediumLabel['FRN'], 'friend'), (apps.contact_book.models.ContactMediumLabel['FAM'], 'family'), (apps.contact_book.models.ContactMediumLabel['OTH'], 'other')], max_length=15)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_book.contact')),
            ],
        ),
        migrations.CreateModel(
            name='ImportantDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('get_alert', models.BooleanField()),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_book.contact')),
                ('important_date_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_book.socialmediasite')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=45)),
                ('label', models.CharField(choices=[(apps.contact_book.models.ContactMediumLabel['BUS'], 'business'), (apps.contact_book.models.ContactMediumLabel['FRN'], 'friend'), (apps.contact_book.models.ContactMediumLabel['FAM'], 'family'), (apps.contact_book.models.ContactMediumLabel['OTH'], 'other')], max_length=15)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_book.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=45)),
                ('postcode', models.CharField(max_length=10)),
                ('address_line_one', models.CharField(max_length=45)),
                ('address_line_two', models.CharField(max_length=45)),
                ('suburb', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('start_of_habitation', models.DateTimeField(null=True)),
                ('end_of_habitation', models.DateTimeField(null=True)),
                ('is_current', models.BooleanField()),
                ('is_hometown', models.BooleanField(null=True)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_book.contact')),
                ('login_of_host_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
