# Generated by Django 3.2.6 on 2021-10-01 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number',
            name='author',
        ),
    ]
