# Generated by Django 3.2.6 on 2021-10-04 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantdate',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='importantdate',
            name='important_date_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_book.importantdatetype'),
        ),
    ]
