# Generated by Django 3.2.6 on 2021-10-11 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book', '0002_auto_20211004_0132'),
        ('contact_book', '0002_auto_20211010_2348'),
    ]

    operations = [
    ]
