# Generated by Django 3.2.6 on 2021-10-01 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book', '0002_remove_number_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='number',
            old_name='contact_id',
            new_name='contact',
        ),
    ]
