# Generated by Django 3.2.6 on 2021-09-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book', '0002_remove_contact_login_of_host_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='department',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='job_title',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='regularity_of_contact',
            field=models.IntegerField(choices=[(104, 'Wk2'), (52, 'Wk1'), (26, 'Frnt'), (12, 'Mnth'), (6, 'Bimt'), (2, 'Yr2'), (1, 'Yr1')], null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='relation',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='side_notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
