# Generated by Django 3.2.6 on 2021-10-11 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact_book', '0002_auto_20211004_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantdatetype',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialmediasite',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialmediasite',
            name='url_format',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='importantdatetype',
            name='icon',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socialmediasite',
            name='icon',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='importantdatetype',
            unique_together={('label', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='socialmediasite',
            unique_together={('site', 'author')},
        ),
        migrations.RemoveField(
            model_name='importantdatetype',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='socialmediasite',
            name='is_default',
        ),
    ]
