# Generated by Django 3.2.6 on 2021-10-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book', '0003_alter_importantdate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line_two',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='end_of_habitation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_current',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_hometown',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='start_of_habitation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='suburb',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='department',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='job_title',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_time_contacted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='middle_name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name_pronunciation',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='nickname',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='pronouns',
            field=models.CharField(blank=True, choices=[('he/him', 'Mal'), ('she/her', 'Fem'), ('they/them', 'Oth')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='regularity_of_contact',
            field=models.IntegerField(blank=True, choices=[(104, 'Wk2'), (52, 'Wk1'), (26, 'Frnt'), (12, 'Mnth'), (6, 'Bimt'), (2, 'Yr2'), (1, 'Yr1')], null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='relation',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='side_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='surname',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='label',
            field=models.CharField(blank=True, choices=[('business', 'Bus'), ('friend', 'Frn'), ('family', 'Fam'), ('other', 'Oth')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='importantdate',
            name='get_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='importantdatetype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='importantdatetype',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='number',
            name='label',
            field=models.CharField(blank=True, choices=[('business', 'Bus'), ('friend', 'Frn'), ('family', 'Fam'), ('other', 'Oth')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasite',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
