# Generated by Django 3.2.6 on 2021-10-01 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book', '0003_rename_contact_id_number_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='contact_id',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='address',
            name='login_of_host_user',
        ),
    ]
