# Generated by Django 3.2.6 on 2021-10-14 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book', '0004_auto_20211011_1035'),
        ('contact_book', '0004_auto_20211012_0654'),
    ]

    operations = [
    ]
