# Generated by Django 3.2.6 on 2021-10-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book', '0004_auto_20211001_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line_two',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='suburb',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
