# Generated by Django 3.2.6 on 2021-10-11 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book', '0002_auto_20211010_2348'),
        ('contact_book', '0004_auto_20211011_1412'),
    ]

    operations = [
    ]
