# Generated by Django 3.2.6 on 2021-10-01 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book', '0005_auto_20211001_0420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='contact_id',
            new_name='contact',
        ),
    ]
