# Generated by Django 3.2.6 on 2021-10-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book', '0005_merge_0004_auto_20211011_1035_0004_auto_20211012_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='last_time_contacted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
