# Generated by Django 3.2.6 on 2021-10-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book', '0006_rename_contact_id_email_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='label',
            field=models.CharField(choices=[('business', 'Bus'), ('friend', 'Frn'), ('family', 'Fam'), ('other', 'Oth')], max_length=15, null=True),
        ),
    ]
