# Generated by Django 3.2.6 on 2021-10-15 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book', '0005_add_default_sites_date_types'),
        ('contact_book', '0006_alter_contact_last_time_contacted'),
    ]

    operations = [
    ]
