# Generated by Django 3.2.6 on 2021-10-16 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book', '0007_alter_number_number'),
        ('contact_book', '0007_merge_20211016_0255'),
    ]

    operations = [
    ]
