# Generated by Django 3.2.6 on 2021-10-16 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book', '0007_merge_20211015_0337'),
        ('contact_book', '0008_merge_20211016_0455'),
    ]

    operations = [
    ]
