# Generated by Django 3.2.6 on 2021-10-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book', '0009_merge_20211016_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line_one',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line_two',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='email_address',
            field=models.EmailField(max_length=320),
        ),
        migrations.AlterField(
            model_name='socialmediacontact',
            name='link',
            field=models.CharField(max_length=300),
        ),
    ]
