# Generated by Django 3.2.6 on 2021-10-28 11:36

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book', '0010_auto_20211017_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
