# Generated by Django 3.2.6 on 2021-09-09 05:02

from django.db import migrations, models
import django.db.models.deletion
import pcrm.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('ContactId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=45)),
                ('Surname', models.CharField(max_length=45)),
                ('MiddleName', models.CharField(max_length=45)),
                ('Nickname', models.CharField(max_length=45)),
                ('NamePronunciation', models.CharField(max_length=45)),
                ('Pronouns', models.CharField(choices=[(pcrm.models.PronounsChoice['MAL'], 'he/him'), (pcrm.models.PronounsChoice['FEM'], 'she/her'), (pcrm.models.PronounsChoice['OTH'], 'they/them')], max_length=15)),
                ('LastTimeContacted', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('LoginEmail', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('DateCreated', models.DateTimeField()),
                ('Password', models.CharField(max_length=45)),
                ('LinkedToContactId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pcrm.contact')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='LoginOfHostUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcrm.user'),
        ),
    ]
