# Generated by Django 3.2.6 on 2021-10-11 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book', '0004_auto_20211011_1035'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='connected_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contact_book.contact'),
        ),
    ]
