# Generated by Django 3.2.6 on 2021-10-15 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_user_business_card_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.EmailValidator]),
        ),
    ]
