# Generated by Django 3.2.6 on 2021-10-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_user_business_card_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_card_theme',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
