# Generated by Django 3.2.6 on 2021-10-16 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_business_card_theme'),
        ('account', '0007_alter_user_email'),
    ]

    operations = [
    ]
