# Generated by Django 3.2.6 on 2021-10-04 01:32

import apps.calendar.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('is_all_day', models.BooleanField()),
                ('location', models.CharField(max_length=45, null=True)),
                ('notes', models.TextField(null=True)),
                ('url', models.CharField(max_length=300, null=True)),
                ('tag', models.CharField(choices=[(apps.calendar.models.EventTag['BUS'], 'business'), (apps.calendar.models.EventTag['FRN'], 'friend'), (apps.calendar.models.EventTag['FAM'], 'family'), (apps.calendar.models.EventTag['PER'], 'personal'), (apps.calendar.models.EventTag['OTH'], 'other')], max_length=15)),
                ('response', models.CharField(choices=[(apps.calendar.models.EventResponse['GOI'], 'going'), (apps.calendar.models.EventResponse['TEN'], 'tentative'), (apps.calendar.models.EventResponse['DEC'], 'declined')], max_length=15)),
                ('is_public', models.BooleanField()),
                ('alert', models.DateTimeField(null=True)),
                ('login_of_host_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar.event')),
                ('login_of_host_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
