name: Django CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: mobius
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt
    - name: Ensure migration files are in sync
#      add environment variables here:
#
#      env:
#        SECRET_KEY: 69tgugtg%^fgJO&*&
#        DB_NAME: mydb
#        DB_USER: userdb
#        DB_PASSWORD: password
#        DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 [::1]
#        DEBUG_MODE: False
#        TIME_ZONE: Africa/Bangui
#        CACHE_KEY_PREFIX: Halo
      run: |
        python3 manage.py makemigrations --check --dry-run
    - name: Run tests
      run: |
        python3 manage.py test

