name: Frontend lint + run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            frontend:
              - 'frontend/**'
              - 'package.json'
              - 'package-lock.json'
      - uses: actions/checkout@v2
      - if: steps.changes.outputs.frontend == 'true'
        name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - if: steps.changes.outputs.frontend == 'true'
        run: npm ci
      - if: steps.changes.outputs.frontend == 'true'
        run: npm run lint
      - if: steps.changes.outputs.frontend == 'true'
        run: npm run test:unit
